import { withTV } from 'tailwind-variants/transformer';

/** @type {import('tailwindcss').Config} */
export default withTV({
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        mfb: {
          brand: {
            100: 'rgba(var(--colors-mfb-primary-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-mfb-primary-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-mfb-primary-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-mfb-primary-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-mfb-primary-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-mfb-primary-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-mfb-primary-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-mfb-primary-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-mfb-primary-900-value), <alpha-value>)',
          },
          secondary: {
            100: 'rgba(var(--colors-mfb-secondary-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-mfb-secondary-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-mfb-secondary-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-mfb-secondary-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-mfb-secondary-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-mfb-secondary-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-mfb-secondary-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-mfb-secondary-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-mfb-secondary-900-value), <alpha-value>)',
          },
          support: {
            100: 'rgba(var(--colors-mfb-support-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-mfb-support-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-mfb-support-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-mfb-support-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-mfb-support-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-mfb-support-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-mfb-support-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-mfb-support-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-mfb-support-900-value), <alpha-value>)',
          },
          neutral: {
            100: 'rgba(var(--colors-mfb-neutral-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-mfb-neutral-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-mfb-neutral-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-mfb-neutral-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-mfb-neutral-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-mfb-neutral-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-mfb-neutral-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-mfb-neutral-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-mfb-neutral-900-value), <alpha-value>)',
          }
        },
        bb: {
          brand: {
            100: 'rgba(var(--colors-bb-primary-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-bb-primary-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-bb-primary-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-bb-primary-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-bb-primary-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-bb-primary-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-bb-primary-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-bb-primary-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-bb-primary-900-value), <alpha-value>)',
          },
          secondary: {
            100: 'rgba(var(--colors-bb-secondary-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-bb-secondary-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-bb-secondary-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-bb-secondary-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-bb-secondary-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-bb-secondary-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-bb-secondary-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-bb-secondary-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-bb-secondary-900-value), <alpha-value>)',
          },
          support: {
            100: 'rgba(var(--colors-bb-support-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-bb-support-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-bb-support-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-bb-support-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-bb-support-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-bb-support-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-bb-support-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-bb-support-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-bb-support-900-value), <alpha-value>)',
          },
          neutral: {
            100: 'rgba(var(--colors-bb-neutral-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-bb-neutral-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-bb-neutral-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-bb-neutral-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-bb-neutral-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-bb-neutral-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-bb-neutral-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-bb-neutral-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-bb-neutral-900-value), <alpha-value>)',
          }
        },
        fs: {
          brand: {
            100: 'rgba(var(--colors-fs-primary-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-fs-primary-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-fs-primary-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-fs-primary-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-fs-primary-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-fs-primary-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-fs-primary-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-fs-primary-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-fs-primary-900-value), <alpha-value>)',
          },
          secondary: {
            100: 'rgba(var(--colors-fs-secondary-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-fs-secondary-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-fs-secondary-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-fs-secondary-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-fs-secondary-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-fs-secondary-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-fs-secondary-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-fs-secondary-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-fs-secondary-900-value), <alpha-value>)',
          },
          support: {
            100: 'rgba(var(--colors-fs-support-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-fs-support-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-fs-support-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-fs-support-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-fs-support-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-fs-support-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-fs-support-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-fs-support-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-fs-support-900-value), <alpha-value>)',
          },
          neutral: {
            100: 'rgba(var(--colors-fs-neutral-100-value), <alpha-value>)',
            200: 'rgba(var(--colors-fs-neutral-200-value), <alpha-value>)',
            300: 'rgba(var(--colors-fs-neutral-300-value), <alpha-value>)',
            400: 'rgba(var(--colors-fs-neutral-400-value), <alpha-value>)',
            500: 'rgba(var(--colors-fs-neutral-500-value), <alpha-value>)',
            600: 'rgba(var(--colors-fs-neutral-600-value), <alpha-value>)',
            700: 'rgba(var(--colors-fs-neutral-700-value), <alpha-value>)',
            800: 'rgba(var(--colors-fs-neutral-800-value), <alpha-value>)',
            900: 'rgba(var(--colors-fs-neutral-900-value), <alpha-value>)',
          }
        }
      },
    },
  },
  plugins: [],
  corePlugins: {
    // preflight: true,
  },
  prefix: 'tw-'
});
